<?php
/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * hereistand implementation : © CONTRIBUTORS
 *
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * hereistand game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */

require_once 'modules/php/constants.inc.php';

$this->cities = [
	LYON => [
		"x" => 2430,
		"y" => 1567,
		"name" => "Lyon",
	],
];

$this->tokens = [
	ENGLAND_KEY => [
		"name" => "English Key",
		"power" => ENGLAND,
		"style" => "Keys england_key",
		"db_id" => "england_scm_{INDEX}",
	],
	FRANCE_KEY => [
		"name" => "French Key",
		"power" => FRANCE,
		"style" => "Keys france_key",
		"db_id" => "tbd_1_{INDEX}",
	],
	HABSBURG_KEY => [
		"name" => "Habsburg Key",
		"power" => HAPSBURG,
		"style" => "Keys habsburg_key",
		"db_id" => "tbd_2_{INDEX}",
	],
	OTTOMAN_KEY => [
		"name" => "Ottoman Key",
		"power" => OTTOMAN,
		"style" => "Keys ottoman_key",
		"db_id" => "tbd_3_{INDEX}",
	],
	INDEPENDENT_KEY => [
		"name" => "Independent Key",
		"power" => OTHER,
		"style" => "Keys independent_key",
		"db_id" => "tbd_4_{INDEX}",
	],
	PAPACY_KEY => [
		"name" => "Papacy Key",
		"power" => PAPACY,
		"style" => "Keys papacy_key",
		"db_id" => "tbd_5_{INDEX}",
	],
	ENGLAND_HEX => [
		"name" => "English Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers england_hex",
		"db_id" => "tbd_6_{INDEX}",
	],
	FRANCE_HEX => [
		"name" => "French Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers france_hex",
		"db_id" => "tbd_7_{INDEX}",
	],
	HABSBURG_HEX => [
		"name" => "Habsburg Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers habsburg_hex",
		"db_id" => "tbd_8_{INDEX}",
	],
	INDEPENDENT_HEX => [
		"name" => "Independent Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers independent_hex",
		"db_id" => "tbd_9_{INDEX}",
	],
	OTTOMAN_HEX => [
		"name" => "Ottoman Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers ottoman_hex",
		"db_id" => "tbd_10_{INDEX}",
	],
	PAPACY_HEX => [
		"name" => "Papacy Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers papacy_hex",
		"db_id" => "tbd_11_{INDEX}",
	],
	PROTESTANT_HEX => [
		"name" => "Protestant Hexagonal Marker",
		"power" => OTHER,
		"style" => "Hex Markers protestant_hex",
		"db_id" => "tbd_12_{INDEX}",
	],
	ENGLAND_1UNIT => [
		"name" => "English 1 Military Unit",
		"power" => ENGLAND,
		"style" => "Military Units england_1unit",
		"db_id" => "england_1unit_{INDEX}",
	],
	ENGLAND_2UNIT => [
		"name" => "English 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units england_2unit",
		"db_id" => "tbd_14_{INDEX}",
	],
	ENGLAND_4UNIT => [
		"name" => "English 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units england_4unit",
		"db_id" => "tbd_15_{INDEX}",
	],
	ENGLAND_6UNIT => [
		"name" => "English 6 Military Unit",
		"power" => OTHER,
		"style" => "Military Units england_6unit",
		"db_id" => "tbd_16",
	],
	FRANCE_1UNIT => [
		"name" => "French 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units france_1unit",
		"db_id" => "tbd_17_{INDEX}",
	],
	FRANCE_2UNIT => [
		"name" => "French 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units france_2unit",
		"db_id" => "tbd_18_{INDEX}",
	],
	FRANCE_4UNIT => [
		"name" => "French 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units france_4unit",
		"db_id" => "tbd_19_{INDEX}",
	],
	FRANCE_6UNIT => [
		"name" => "French 6 Military Unit",
		"power" => OTHER,
		"style" => "Military Units france_6unit",
		"db_id" => "tbd_20",
	],
	GENOA_1UNIT => [
		"name" => "Genoese 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units genoa_1unit",
		"db_id" => "tbd_21",
	],
	GENOA_2UNIT => [
		"name" => "Genoese 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units genoa_2unit",
		"db_id" => "tbd_22",
	],
	HABSBURG_1UNIT => [
		"name" => "Habsburg 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units habsburg_1unit",
		"db_id" => "tbd_23_{INDEX}",
	],
	HABSBURG_2UNIT => [
		"name" => "Habsburg 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units habsburg_2unit",
		"db_id" => "tbd_24_{INDEX}",
	],
	HABSBURG_4UNIT => [
		"name" => "Habsburg 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units habsburg_4unit",
		"db_id" => "tbd_25_{INDEX}",
	],
	HABSBURG_6UNIT => [
		"name" => "Habsburg 6 Military Unit",
		"power" => OTHER,
		"style" => "Military Units habsburg_6unit",
		"db_id" => "tbd_26",
	],
	HUNGARY_1UNIT => [
		"name" => "Hungarian 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units hungary_1unit",
		"db_id" => "tbd_27_{INDEX}",
	],
	HUNGARY_4UNIT => [
		"name" => "Hungarian 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units hungary_4unit",
		"db_id" => "tbd_28",
	],
	INDEPENDENT_1UNIT => [
		"name" => "Independent 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units independent_1unit",
		"db_id" => "tbd_29_{INDEX}",
	],
	KNIGHTS_1UNIT => [
		"name" => "Knights of Saint John 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units knights_1unit",
		"db_id" => "tbd_30",
	],
	OTTOMAN_1UNIT => [
		"name" => "Ottoman 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units ottoman_1unit",
		"db_id" => "tbd_31_{INDEX}",
	],
	OTTOMAN_2UNIT => [
		"name" => "Ottoman 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units ottoman_2unit",
		"db_id" => "tbd_32_{INDEX}",
	],
	OTTOMAN_4UNIT => [
		"name" => "Ottoman 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units ottoman_4unit",
		"db_id" => "tbd_33_{INDEX}",
	],
	OTTOMAN_6UNIT => [
		"name" => "Ottoman 6 Military Unit",
		"power" => OTHER,
		"style" => "Military Units ottoman_6unit",
		"db_id" => "tbd_34",
	],
	PAPACY_1UNIT => [
		"name" => "Papacy 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units papacy_1unit",
		"db_id" => "tbd_35_{INDEX}",
	],
	PAPACY_2UNIT => [
		"name" => "Papacy 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units papacy_2unit",
		"db_id" => "tbd_36_{INDEX}",
	],
	PAPACY_4UNIT => [
		"name" => "Papacy 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units papacy_4unit",
		"db_id" => "tbd_37_{INDEX}",
	],
	PROTESTANT_1UNIT => [
		"name" => "Protestant 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units protestant_1unit",
		"db_id" => "tbd_38_{INDEX}",
	],
	PROTESTANT_2UNIT => [
		"name" => "Protestant 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units protestant_2unit",
		"db_id" => "tbd_39_{INDEX}",
	],
	PROTESTANT_4UNIT => [
		"name" => "Protestant 4 Military Unit",
		"power" => OTHER,
		"style" => "Military Units protestant_4unit",
		"db_id" => "tbd_40_{INDEX}",
	],
	SCOTLAND_1UNIT => [
		"name" => "Scottish 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units scotland_1unit",
		"db_id" => "tbd_41_{INDEX}",
	],
	SCOTLAND_2UNIT => [
		"name" => "Scottish 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units scotland_2unit",
		"db_id" => "tbd_42",
	],
	VENICE_1UNIT => [
		"name" => "Venetian 1 Military Unit",
		"power" => OTHER,
		"style" => "Military Units venice_1unit",
		"db_id" => "tbd_43",
	],
	VENICE_2UNIT => [
		"name" => "Venetian 2 Military Unit",
		"power" => OTHER,
		"style" => "Military Units venice_2unit",
		"db_id" => "tbd_44",
	],
	BRANDON => [
		"name" => "Brandon",
		"power" => OTHER,
		"style" => "Leader brandon",
		"db_id" => "brandon",
	],
	CHARLES_V => [
		"name" => "Charles V",
		"power" => OTHER,
		"style" => "Leader charles_v",
		"db_id" => "charles_v",
	],
	DUDLEY => [
		"name" => "Dudley",
		"power" => OTHER,
		"style" => "Leader dudley",
		"db_id" => "dudly",
	],
	DUKE_ALVA => [
		"name" => "Duke of Alva",
		"power" => OTHER,
		"style" => "Leader duke_alva",
		"db_id" => "duke_alva",
	],
	FERDINAND => [
		"name" => "Ferdinand",
		"power" => OTHER,
		"style" => "Leader ferdinand",
		"db_id" => "tbd_49",
	],
	FRANCIS_I => [
		"name" => "Francis I",
		"power" => OTHER,
		"style" => "Leader francis_i",
		"db_id" => "tbd_50",
	],
	HENRY_II => [
		"name" => "Henry II",
		"power" => OTHER,
		"style" => "Leader henry_ii",
		"db_id" => "tbd_51",
	],
	HENRY_VIII => [
		"name" => "Henry VIII",
		"power" => OTHER,
		"style" => "Leader henry_viii",
		"db_id" => "tbd_52",
	],
	IBRAHIM => [
		"name" => "Ibrahim",
		"power" => OTHER,
		"style" => "Leader ibrahim",
		"db_id" => "tbd_53",
	],
	JOHN_FREDERICK => [
		"name" => "John Frederick",
		"power" => OTHER,
		"style" => "Leader john_frederick",
		"db_id" => "tbd_54",
	],
	MAURICE_OF_SAXONY => [
		"name" => "Maurice of Saxony",
		"power" => OTHER,
		"style" => "Leader maurice_of_saxony",
		"db_id" => "maurice_of_saxony",
	],
	MONTMORENCY => [
		"name" => "Montmorency",
		"power" => OTHER,
		"style" => "Leader montmorency",
		"db_id" => "tbd_56",
	],
	PHILIP_HESSE => [
		"name" => "Philip of Hesse",
		"power" => OTHER,
		"style" => "Leader philip_hesse",
		"db_id" => "tbd_57",
	],
	RENEGADE => [
		"name" => "Charles Borbon, Renegade Leader",
		"power" => OTHER,
		"style" => "Leader renegade",
		"db_id" => "tbd_58",
	],
	SULEIMAN => [
		"name" => "Suleiman",
		"power" => OTHER,
		"style" => "Leader suleiman",
		"db_id" => "tbd_59",
	],
	ENGLISH_SQUADRON => [
		"name" => "English Squadron",
		"power" => OTHER,
		"style" => "Naval Units english_squadron",
		"db_id" => "tbd_60_{INDEX}",
	],
	FRENCH_SQUADRON => [
		"name" => "French Squadron",
		"power" => OTHER,
		"style" => "Naval Units french_squadron",
		"db_id" => "tbd_61_{INDEX}",
	],
	GENOESE_SQAUADRON => [
		"name" => "Genoese Squadron",
		"power" => OTHER,
		"style" => "Naval Units genoese_sqauadron",
		"db_id" => "tbd_62",
	],
	HABSBURG_SQUADRON => [
		"name" => "Habsburg Squadron",
		"power" => OTHER,
		"style" => "Naval Units habsburg_squadron",
		"db_id" => "tbd_63_{INDEX}",
	],
	OTTOMAN_SQUADRON => [
		"name" => "Ottoman Squadron",
		"power" => OTHER,
		"style" => "Naval Units ottoman_squadron",
		"db_id" => "tbd_64_{INDEX}",
	],
	PAPACY_SQUADRON => [
		"name" => "Papacy Squadron",
		"power" => OTHER,
		"style" => "Naval Units papacy_squadron",
		"db_id" => "tbd_65_{INDEX}",
	],
	SCOTTISH_SQUADRON => [
		"name" => "Scottish Squadron",
		"power" => OTHER,
		"style" => "Naval Units scottish_squadron",
		"db_id" => "tbd_66",
	],
	VENETIAN_SQUADRON => [
		"name" => "Venetian Squadron",
		"power" => OTHER,
		"style" => "Naval Units venetian_squadron",
		"db_id" => "tbd_67_{INDEX}",
	],
	ANDREA_DORIA => [
		"name" => "Andrea Doria",
		"power" => OTHER,
		"style" => "Naval Leader andrea_doria",
		"db_id" => "tbd_68",
	],
	BARBAROSSA => [
		"name" => "Barbarossa",
		"power" => OTHER,
		"style" => "Naval Leader barbarossa",
		"db_id" => "tbd_69",
	],
	DRAGUT => [
		"name" => "Dragut",
		"power" => OTHER,
		"style" => "Naval Leader dragut",
		"db_id" => "tbd_70",
	],
	ALLIED => [
		"name" => "Allied",
		"power" => OTHER,
		"style" => "Diplomacy allied",
		"db_id" => "tbd_71_{INDEX}",
	],
	AT_WAR => [
		"name" => "At War",
		"power" => OTHER,
		"style" => "Diplomacy at_war",
		"db_id" => "tbd_72_{INDEX}",
	],
	UNREST => [
		"name" => "Unrest",
		"power" => OTHER,
		"style" => "Unrest unrest",
		"db_id" => "tbd_73_{INDEX}",
	],
	VP_ENGLAND => [
		"name" => "English VP's",
		"power" => OTHER,
		"style" => "VP Counter vp_england",
		"db_id" => "tbd_74",
	],
	VP_FRANCE => [
		"name" => "French VP's",
		"power" => OTHER,
		"style" => "VP Counter vp_france",
		"db_id" => "tbd_75",
	],
	VP_HABSBURG => [
		"name" => "Habsburg VP's",
		"power" => OTHER,
		"style" => "VP Counter vp_habsburg",
		"db_id" => "tbd_76",
	],
	VP_OTTOMAN => [
		"name" => "Ottoman VP's",
		"power" => OTHER,
		"style" => "VP Counter vp_ottoman",
		"db_id" => "tbd_77",
	],
	VP_PAPACY => [
		"name" => "Papacy VP's",
		"power" => OTHER,
		"style" => "VP Counter vp_papacy",
		"db_id" => "tbd_78",
	],
	VP_PROTESTANT => [
		"name" => "Protestant VP's",
		"power" => OTHER,
		"style" => "VP Counter vp_protestant",
		"db_id" => "tbd_79",
	],
	LOANED_ENGLAND => [
		"name" => "Loaned to England",
		"power" => OTHER,
		"style" => "Loaned loaned_england",
		"db_id" => "tbd_80_{INDEX}",
	],
	LOANED_FRANCE => [
		"name" => "Loaned to France",
		"power" => OTHER,
		"style" => "Loaned loaned_france",
		"db_id" => "tbd_81_{INDEX}",
	],
	LOANED_HABSBURG => [
		"name" => "Loaned to Habsburg",
		"power" => OTHER,
		"style" => "Loaned loaned_habsburg",
		"db_id" => "tbd_82_{INDEX}",
	],
	LOANED_OTTOMAN => [
		"name" => "Loaned to Ottoman",
		"power" => OTHER,
		"style" => "Loaned loaned_ottoman",
		"db_id" => "tbd_83_{INDEX}",
	],
	LOANED_PAPACY => [
		"name" => "Loaned to Papacy",
		"power" => OTHER,
		"style" => "Loaned loaned_papacy",
		"db_id" => "tbd_84_{INDEX}",
	],
	CALVIN_REFORMER => [
		"name" => "Calvin Reformer",
		"power" => OTHER,
		"style" => "Reformer calvin_reformer",
		"db_id" => "tbd_85",
	],
	CRANMER_REFORMER => [
		"name" => "Cranmer Reformer",
		"power" => OTHER,
		"style" => "Reformer cranmer_reformer",
		"db_id" => "tbd_86",
	],
	LUTHER_REFORMER => [
		"name" => "Luther Reformer",
		"power" => OTHER,
		"style" => "Reformer luther_reformer",
		"db_id" => "tbd_87",
	],
	ZWINGLI_REFORMER => [
		"name" => "Zwingli Reformer",
		"power" => OTHER,
		"style" => "Reformer zwingli_reformer",
		"db_id" => "tbd_88",
	],
	ALEANDER => [
		"name" => "Aleander",
		"power" => OTHER,
		"style" => "Debater aleander",
		"db_id" => "tbd_89",
	],
	CAJETAN => [
		"name" => "Cajetan",
		"power" => OTHER,
		"style" => "Debater cajetan",
		"db_id" => "tbd_90",
	],
	CAMPEGGIO => [
		"name" => "Campeggio",
		"power" => OTHER,
		"style" => "Debater campeggio",
		"db_id" => "tbd_91",
	],
	CANISIUS => [
		"name" => "Canisius",
		"power" => OTHER,
		"style" => "Debater canisius",
		"db_id" => "tbd_92",
	],
	CARAFFA => [
		"name" => "Caraffa",
		"power" => OTHER,
		"style" => "Debater caraffa",
		"db_id" => "tbd_93",
	],
	CONTARINI => [
		"name" => "Contarini",
		"power" => OTHER,
		"style" => "Debater contarini",
		"db_id" => "tbd_94",
	],
	ECK => [
		"name" => "Eck",
		"power" => OTHER,
		"style" => "Debater eck",
		"db_id" => "tbd_95",
	],
	FABER => [
		"name" => "Faber",
		"power" => OTHER,
		"style" => "Debater faber",
		"db_id" => "tbd_96",
	],
	GARDINER => [
		"name" => "Gardiner",
		"power" => OTHER,
		"style" => "Debater gardiner",
		"db_id" => "tbd_97",
	],
	LOYOLA => [
		"name" => "Loyola",
		"power" => OTHER,
		"style" => "Debater loyola",
		"db_id" => "tbd_98",
	],
	POLE => [
		"name" => "Pole",
		"power" => OTHER,
		"style" => "Debater pole",
		"db_id" => "tbd_99",
	],
	TETZEL => [
		"name" => "Tetzel",
		"power" => OTHER,
		"style" => "Debater tetzel",
		"db_id" => "tbd_100",
	],
	BUCER => [
		"name" => "Bucer",
		"power" => OTHER,
		"style" => "Debater bucer",
		"db_id" => "tbd_101",
	],
	BULLINGER => [
		"name" => "Bullinger",
		"power" => OTHER,
		"style" => "Debater bullinger",
		"db_id" => "tbd_102",
	],
	CALVIN => [
		"name" => "Calvin",
		"power" => OTHER,
		"style" => "Debater calvin",
		"db_id" => "tbd_103",
	],
	CARLSTADT => [
		"name" => "Carlstadt",
		"power" => OTHER,
		"style" => "Debater carlstadt",
		"db_id" => "tbd_104",
	],
	COP => [
		"name" => "Cop",
		"power" => OTHER,
		"style" => "Debater cop",
		"db_id" => "tbd_105",
	],
	COVERDALE => [
		"name" => "Coverdale",
		"power" => OTHER,
		"style" => "Debater coverdale",
		"db_id" => "tbd_106",
	],
	CRANMER => [
		"name" => "Cranmer",
		"power" => OTHER,
		"style" => "Debater cranmer",
		"db_id" => "tbd_107",
	],
	FAREL => [
		"name" => "Farel",
		"power" => OTHER,
		"style" => "Debater farel",
		"db_id" => "tbd_108",
	],
	KNOX => [
		"name" => "Knox",
		"power" => OTHER,
		"style" => "Debater knox",
		"db_id" => "tbd_109",
	],
	LATIMER => [
		"name" => "Latimer",
		"power" => OTHER,
		"style" => "Debater latimer",
		"db_id" => "tbd_110",
	],
	LUTHER => [
		"name" => "Luther",
		"power" => OTHER,
		"style" => "Debater luther",
		"db_id" => "tbd_111",
	],
	MELANCHTHON => [
		"name" => "Melanchthon",
		"power" => OTHER,
		"style" => "Debater melanchthon",
		"db_id" => "tbd_112",
	],
	OEKOLAMPADIUS => [
		"name" => "Oekolampadius",
		"power" => OTHER,
		"style" => "Debater oekolampadius",
		"db_id" => "tbd_113",
	],
	OLIVETAN => [
		"name" => "Olivetan",
		"power" => OTHER,
		"style" => "Debater olivetan",
		"db_id" => "tbd_114",
	],
	TYNDALE => [
		"name" => "Tyndale",
		"power" => OTHER,
		"style" => "Debater tyndale",
		"db_id" => "tbd_115",
	],
	WISHART => [
		"name" => "Wishart",
		"power" => OTHER,
		"style" => "Debater wishart",
		"db_id" => "tbd_116",
	],
	ZWINGLI => [
		"name" => "Zwingli",
		"power" => OTHER,
		"style" => "Debater zwingli",
		"db_id" => "tbd_117",
	],
	ENGLISH_EXPLORATION => [
		"name" => "English Exploration Underway",
		"power" => OTHER,
		"style" => "Exploration english_exploration",
		"db_id" => "tbd_118",
	],
	FRENCH_EXPLORATION => [
		"name" => "French Exploration Underway",
		"power" => OTHER,
		"style" => "Exploration french_exploration",
		"db_id" => "tbd_119",
	],
	HABSBURG_EXPLORATION => [
		"name" => "Habsburg Exploration Underway",
		"power" => OTHER,
		"style" => "Exploration habsburg_exploration",
		"db_id" => "tbd_120",
	],
	CABOT_ENG => [
		"name" => "Cabot English",
		"power" => OTHER,
		"style" => "Explorer cabot_eng",
		"db_id" => "tbd_121",
	],
	CABOT_FRE => [
		"name" => "Cabot French",
		"power" => OTHER,
		"style" => "Explorer cabot_fre",
		"db_id" => "tbd_122",
	],
	CABOT_HAB => [
		"name" => "Cabot Habsburg",
		"power" => OTHER,
		"style" => "Explorer cabot_hab",
		"db_id" => "tbd_123",
	],
	CARTIER => [
		"name" => "Cartier",
		"power" => OTHER,
		"style" => "Explorer cartier",
		"db_id" => "tbd_124",
	],
	CHANCELLOR => [
		"name" => "Chancellor",
		"power" => OTHER,
		"style" => "Explorer chancellor",
		"db_id" => "tbd_125",
	],
	DE_VACA => [
		"name" => "De Vaca",
		"power" => OTHER,
		"style" => "Explorer de_vaca",
		"db_id" => "tbd_126",
	],
	DE_SOTO => [
		"name" => "De Soto",
		"power" => OTHER,
		"style" => "Explorer de_soto",
		"db_id" => "tbd_127",
	],
	LEON => [
		"name" => "Leon",
		"power" => OTHER,
		"style" => "Explorer leon",
		"db_id" => "tbd_128",
	],
	MAGELLAN => [
		"name" => "Magellan",
		"power" => OTHER,
		"style" => "Explorer magellan",
		"db_id" => "tbd_129",
	],
	NARVAEZ => [
		"name" => "Narvaez",
		"power" => OTHER,
		"style" => "Explorer narvaez",
		"db_id" => "tbd_130",
	],
	ORELLANA => [
		"name" => "Orellana",
		"power" => OTHER,
		"style" => "Explorer orellana",
		"db_id" => "tbd_131",
	],
	ROBERVAL => [
		"name" => "Roberval",
		"power" => OTHER,
		"style" => "Explorer roberval",
		"db_id" => "tbd_132",
	],
	RUT => [
		"name" => "Rut",
		"power" => OTHER,
		"style" => "Explorer rut",
		"db_id" => "tbd_133",
	],
	VERRAZANO => [
		"name" => "Verrazano",
		"power" => OTHER,
		"style" => "Explorer verrazano",
		"db_id" => "tbd_134",
	],
	WILLOUGHBY => [
		"name" => "Willoughby",
		"power" => OTHER,
		"style" => "Explorer willoughby",
		"db_id" => "tbd_135",
	],
	CHARLESBOURG => [
		"name" => "Charlesbourg",
		"power" => OTHER,
		"style" => "Colony charlesbourg",
		"db_id" => "tbd_136",
	],
	CUBA => [
		"name" => "Cuba",
		"power" => OTHER,
		"style" => "Colony cuba",
		"db_id" => "tbd_137",
	],
	HISPANIOLA => [
		"name" => "Hispaniola",
		"power" => OTHER,
		"style" => "Colony hispaniola",
		"db_id" => "tbd_138",
	],
	JAMESTOWN => [
		"name" => "Jamestown",
		"power" => OTHER,
		"style" => "Colony jamestown",
		"db_id" => "tbd_139",
	],
	MONTREAL => [
		"name" => "Montreal",
		"power" => OTHER,
		"style" => "Colony montreal",
		"db_id" => "tbd_140",
	],
	POTOSI => [
		"name" => "Potosi Silver Mines",
		"power" => OTHER,
		"style" => "Colony potosi",
		"db_id" => "tbd_141",
	],
	PUERTO_RICO => [
		"name" => "Puerto Rico",
		"power" => OTHER,
		"style" => "Colony puerto_rico",
		"db_id" => "tbd_142",
	],
	ROANOKE => [
		"name" => "Roanoke",
		"power" => OTHER,
		"style" => "Colony roanoke",
		"db_id" => "tbd_143",
	],
	HABSBURG_CONQUEST => [
		"name" => "Habsburg Conquest Underway",
		"power" => OTHER,
		"style" => "Conquest habsburg_conquest",
		"db_id" => "tbd_144",
	],
	ENGLISH_CONQUEST => [
		"name" => "English Conquest",
		"power" => OTHER,
		"style" => "Conquistador english_conquest",
		"db_id" => "tbd_145_{INDEX}",
	],
	FRENCH_CONQUEST => [
		"name" => "French Conquest",
		"power" => OTHER,
		"style" => "Conquistador french_conquest",
		"db_id" => "tbd_146_{INDEX}",
	],
	CORDOVA => [
		"name" => "Cordova",
		"power" => OTHER,
		"style" => "Conquistador cordova",
		"db_id" => "tbd_147",
	],
	CORONADO => [
		"name" => "Coronado",
		"power" => OTHER,
		"style" => "Conquistador coronado",
		"db_id" => "tbd_148",
	],
	CORTEZ => [
		"name" => "Cortez",
		"power" => OTHER,
		"style" => "Conquistador cortez",
		"db_id" => "tbd_149",
	],
	MONTEJO => [
		"name" => "Montejo",
		"power" => OTHER,
		"style" => "Conquistador montejo",
		"db_id" => "tbd_150",
	],
	PIZARRO => [
		"name" => "Pizarro",
		"power" => OTHER,
		"style" => "Conquistador pizarro",
		"db_id" => "tbd_151",
	],
	ENGLISH_PROT_COUNTER => [
		"name" => "English Home Protestant Spaces",
		"power" => OTHER,
		"style" => "Religious counter english_prot_counter",
		"db_id" => "tbd_152",
	],
	PROTESTANT_SPACES => [
		"name" => "Protestant Spaces",
		"power" => OTHER,
		"style" => "Religious counter protestant_spaces",
		"db_id" => "tbd_153",
	],
	TURN => [
		"name" => "Turn",
		"power" => OTHER,
		"style" => "Turn counter turn",
		"db_id" => "tbd_154",
	],
	MINUS_ONE_CARD => [
		"name" => "-1 Card",
		"power" => OTHER,
		"style" => "Cards Marker minus_one_card",
		"db_id" => "tbd_155_{INDEX}",
	],
	GREAT_LAKES_1VP => [
		"name" => "Great Lakes 1 VP",
		"power" => VP,
		"style" => "VP marker great_lakes_1vp",
		"db_id" => "tbd_156",
	],
	MISSISSIPPI_RIVER_1VP => [
		"name" => "Mississippi River 1 VP",
		"power" => OTHER,
		"style" => "VP marker mississippi_river_1vp",
		"db_id" => "tbd_157",
	],
	ST_LAWRENCE_RIVER_1VP => [
		"name" => "Saint Lawrence River 1 VP",
		"power" => OTHER,
		"style" => "VP marker st_lawrence_river_1vp",
		"db_id" => "tbd_158",
	],
	AMAZON_RIVER_2VP => [
		"name" => "Amazon River 2 VP's",
		"power" => OTHER,
		"style" => "VP marker amazon_river_2vp",
		"db_id" => "tbd_159",
	],
	PACIFIC_STRAIT_1VP => [
		"name" => "Pacific Strait 1 VP",
		"power" => OTHER,
		"style" => "VP marker pacific_strait_1vp",
		"db_id" => "tbd_160",
	],
	CIRCUMNAVIGATION_3VP => [
		"name" => "Circumnavigation 3 VP",
		"power" => OTHER,
		"style" => "VP marker circumnavigation_3vp",
		"db_id" => "tbd_161",
	],
	MAYA_1VP => [
		"name" => "Maya 1 VP",
		"power" => OTHER,
		"style" => "VP marker maya_1vp",
		"db_id" => "tbd_162",
	],
	AZTECS_2VP => [
		"name" => "Aztecs 2 VP's",
		"power" => OTHER,
		"style" => "VP marker aztecs_2vp",
		"db_id" => "tbd_163",
	],
	INCA_2VP => [
		"name" => "Inca 2 VP's",
		"power" => OTHER,
		"style" => "VP marker inca_2vp",
		"db_id" => "inca_2vp",
	],
	BIBLE_ENG_1VP => [
		"name" => "Bible English Translation 1 VP",
		"power" => OTHER,
		"style" => "VP marker bible_eng_1vp",
		"db_id" => "bible_eng_1vp",
	],
	BIBLE_FRE_1VP => [
		"name" => "Bible French Translation 1 VP",
		"power" => OTHER,
		"style" => "VP marker bible_fre_1vp",
		"db_id" => "bible_fre_1vp",
	],
	BIBLE_GER_1VP => [
		"name" => "Bible German Translation 1 VP",
		"power" => OTHER,
		"style" => "VP marker bible_ger_1vp",
		"db_id" => "bible_ger_1vp",
	],
	CHATEAUX_VP => [
		"name" => "Chateaux VP's",
		"power" => OTHER,
		"style" => "VP marker chateaux_vp",
		"db_id" => "tbd_168",
	],
	PIRACY_VP => [
		"name" => "Piracy VP's",
		"power" => OTHER,
		"style" => "VP marker piracy_vp",
		"db_id" => "tbd_169",
	],
	ST_PETERS_VP => [
		"name" => "Saint Peter's VP's",
		"power" => OTHER,
		"style" => "VP marker st_peters_vp",
		"db_id" => "tbd_170",
	],
	COPERNICUS_1VP => [
		"name" => "Copernicus 1 VP",
		"power" => OTHER,
		"style" => "VP marker copernicus_1vp",
		"db_id" => "tbd_171",
	],
	COPERNICUS_2VP => [
		"name" => "Copernicus 2 VP's",
		"power" => OTHER,
		"style" => "VP marker copernicus_2vp",
		"db_id" => "tbd_172",
	],
	EDWARD_5VP => [
		"name" => "Edward VI 5 VP's",
		"power" => OTHER,
		"style" => "VP marker edward_5vp",
		"db_id" => "tbd_173",
	],
	ELIZABETH_2VP => [
		"name" => "Elizabeth 2 VP's",
		"power" => OTHER,
		"style" => "VP marker elizabeth_2vp",
		"db_id" => "tbd_174",
	],
	GONZAGA_1VP => [
		"name" => "Giulia Gonzaga 1 VP",
		"power" => OTHER,
		"style" => "VP marker gonzaga_1vp",
		"db_id" => "tbd_175",
	],
	SERVETUS_1VP => [
		"name" => "Servetus 1 VP",
		"power" => OTHER,
		"style" => "VP marker servetus_1vp",
		"db_id" => "tbd_176",
	],
	MASTER_OF_ITALY_1VP => [
		"name" => "Master of Italy 1 VP",
		"power" => OTHER,
		"style" => "VP marker master_of_italy_1vp",
		"db_id" => "tbd_177_{INDEX}",
	],
	MASTER_OF_ITALY_2VP => [
		"name" => "Master of Italy 2 VP's",
		"power" => OTHER,
		"style" => "VP marker master_of_italy_2vp",
		"db_id" => "tbd_178_{INDEX}",
	],
	WAR_WINNER_1VP => [
		"name" => "War Winner 1 VP",
		"power" => OTHER,
		"style" => "VP marker war_winner_1vp",
		"db_id" => "tbd_179",
	],
	WAR_WINNER_2VP => [
		"name" => "War Winner 2 VP's",
		"power" => OTHER,
		"style" => "VP marker war_winner_2vp",
		"db_id" => "tbd_180",
	],
	PHONYSCOTLAND_MINUS1 => [
		"name" => "Phony War in Scotland -1 VP's",
		"power" => OTHER,
		"style" => "VP marker phonyscotland_minus1",
		"db_id" => "tbd_181",
	],
	PHONYVENICE_MINUS1 => [
		"name" => "Phony War in Venice - 1 VP's",
		"power" => OTHER,
		"style" => "VP marker phonyvenice_minus1",
		"db_id" => "tbd_182",
	],
	ANNE_BOLEYN => [
		"name" => "Anne Boleyn",
		"power" => OTHER,
		"style" => "Wife anne_boleyn",
		"db_id" => "tbd_183",
	],
	ANNE_CLEVES => [
		"name" => "Anne of Cleves",
		"power" => OTHER,
		"style" => "Wife anne_cleves",
		"db_id" => "tbd_184",
	],
	CATHERINE_ARAGON => [
		"name" => "Catherine of Aragon",
		"power" => OTHER,
		"style" => "Wife catherine_aragon",
		"db_id" => "tbd_185",
	],
	JANE_SEYMOUR => [
		"name" => "Jane Seymour",
		"power" => OTHER,
		"style" => "Wife jane_seymour",
		"db_id" => "tbd_186",
	],
	KATHERINE_PARR => [
		"name" => "Katherine Parr",
		"power" => OTHER,
		"style" => "Wife katherine_parr",
		"db_id" => "tbd_187",
	],
	KATHRYN_HOWARD => [
		"name" => "Kathryn Howard",
		"power" => OTHER,
		"style" => "Wife kathryn_howard",
		"db_id" => "tbd_188",
	],
	HENRY_MARITAL_STATUS => [
		"name" => "Henry Marital Status",
		"power" => OTHER,
		"style" => "Wives Status henry_marital_status",
		"db_id" => "tbd_189",
	],
	BIBLE_ENGLISH => [
		"name" => "Bible English",
		"power" => OTHER,
		"style" => "Translation bible_english",
		"db_id" => "tbd_190",
	],
	BIBLE_FRENCH => [
		"name" => "Bible French",
		"power" => OTHER,
		"style" => "Translation bible_french",
		"db_id" => "tbd_191",
	],
	BIBLE_GERMAN => [
		"name" => "Bible German",
		"power" => OTHER,
		"style" => "Translation bible_german",
		"db_id" => "tbd_192",
	],
	NEW_TESTAMENT_ENGLISH => [
		"name" => "New Testament English",
		"power" => OTHER,
		"style" => "Translation new_testament_english",
		"db_id" => "tbd_193",
	],
	NEW_TESTAMENT_FRENCH => [
		"name" => "New Testament French",
		"power" => OTHER,
		"style" => "Translation new_testament_french",
		"db_id" => "tbd_194",
	],
	NEW_TESTAMENT_GERMAN => [
		"name" => "New Testament German",
		"power" => OTHER,
		"style" => "Translation new_testament_german",
		"db_id" => "tbd_195",
	],
	ST_PETERS_CP => [
		"name" => "Saint Peter's CP Status",
		"power" => OTHER,
		"style" => "Saint Peter's st_peters_cp",
		"db_id" => "tbd_196",
	],
	AUGSBURG_CONFESSION => [
		"name" => "Augsburg Confession Active",
		"power" => OTHER,
		"style" => "Event reminder augsburg_confession",
		"db_id" => "tbd_197",
	],
	PRINTING_PRESS => [
		"name" => "Printing Press Active",
		"power" => OTHER,
		"style" => "Event reminder printing_press",
		"db_id" => "tbd_198",
	],
	COLONIAL_GOVERNOR => [
		"name" => "Colonial Governor",
		"power" => OTHER,
		"style" => "Event reminder colonial_governor",
		"db_id" => "tbd_199_{INDEX}",
	],
	GALLEONS => [
		"name" => "Galleons",
		"power" => OTHER,
		"style" => "Event reminder galleons",
		"db_id" => "tbd_200_{INDEX}",
	],
	PLANTATIONS => [
		"name" => "Plantations",
		"power" => OTHER,
		"style" => "Event reminder plantations",
		"db_id" => "tbd_201_{INDEX}",
	],
	PIRACY => [
		"name" => "Piracy Marker",
		"power" => OTHER,
		"style" => "Event reminder piracy",
		"db_id" => "tbd_202",
	],
	NATIVE_UPRISING => [
		"name" => "Native Uprising",
		"power" => OTHER,
		"style" => "Event reminder native_uprising",
		"db_id" => "tbd_203_{INDEX}",
	],
	RAIDER_ENGLISH => [
		"name" => "English Huguenot Raider",
		"power" => OTHER,
		"style" => "Event reminder raider_english",
		"db_id" => "tbd_204",
	],
	RAIDER_FRENCH => [
		"name" => "French Huguenot Raider",
		"power" => OTHER,
		"style" => "Event reminder raider_french",
		"db_id" => "tbd_205",
	],
	RAIDER_PROTESTANT => [
		"name" => "Protestant Huguenot Raider",
		"power" => OTHER,
		"style" => "Event reminder raider_protestant",
		"db_id" => "tbd_206",
	],
	MERCATOR_MAP => [
		"name" => "Mercator's Map",
		"power" => OTHER,
		"style" => "Event reminder mercator_map",
		"db_id" => "tbd_207",
	],
	SMALLPOX => [
		"name" => "Smallpox",
		"power" => OTHER,
		"style" => "Event reminder smallpox",
		"db_id" => "tbd_208",
	],
	THOMAS_MORE => [
		"name" => "Thomas More",
		"power" => OTHER,
		"style" => "Event reminder thomas_more",
		"db_id" => "tbd_209",
	],
	WARTBURG => [
		"name" => "Wartburg",
		"power" => OTHER,
		"style" => "Event reminder wartburg",
		"db_id" => "tbd_210",
	],
	EXCOMMUNICATED => [
		"name" => "Excommunicated",
		"power" => OTHER,
		"style" => "Excommunion excommunicated",
		"db_id" => "tbd_211_{INDEX}",
	],
	FORTRESS => [
		"name" => "Fortress",
		"power" => OTHER,
		"style" => "Fortress fortress",
		"db_id" => "tbd_212_{INDEX}",
	],
	PIRATE_HAVEN => [
		"name" => "Pirate Haven",
		"power" => OTHER,
		"style" => "Pirate Haven pirate_haven",
		"db_id" => "tbd_213_{INDEX}",
	],
	JESUIT_UNIVERSITY => [
		"name" => "Jesuit University",
		"power" => OTHER,
		"style" => "University jesuit_university",
		"db_id" => "tbd_214",
	],
];

$this->starting_token_counts = [
	ENGLAND_KEY => 9,
	FRANCE_KEY => 11,
	HABSBURG_KEY => 14,
	OTTOMAN_KEY => 11,
	INDEPENDENT_KEY => 18,
	PAPACY_KEY => 7,
	ENGLAND_HEX => 100,
	FRANCE_HEX => 100,
	HABSBURG_HEX => 100,
	INDEPENDENT_HEX => 31,
	OTTOMAN_HEX => 100,
	PAPACY_HEX => 100,
	PROTESTANT_HEX => 100,
	ENGLAND_1UNIT => 9,
	ENGLAND_2UNIT => 5,
	ENGLAND_4UNIT => 2,
	ENGLAND_6UNIT => 1,
	FRANCE_1UNIT => 10,
	FRANCE_2UNIT => 4,
	FRANCE_4UNIT => 3,
	FRANCE_6UNIT => 1,
	GENOA_1UNIT => 1,
	GENOA_2UNIT => 1,
	HABSBURG_1UNIT => 12,
	HABSBURG_2UNIT => 7,
	HABSBURG_4UNIT => 4,
	HABSBURG_6UNIT => 1,
	HUNGARY_1UNIT => 3,
	HUNGARY_4UNIT => 1,
	INDEPENDENT_1UNIT => 6,
	KNIGHTS_1UNIT => 1,
	OTTOMAN_1UNIT => 11,
	OTTOMAN_2UNIT => 7,
	OTTOMAN_4UNIT => 4,
	OTTOMAN_6UNIT => 1,
	PAPACY_1UNIT => 7,
	PAPACY_2UNIT => 4,
	PAPACY_4UNIT => 2,
	PROTESTANT_1UNIT => 8,
	PROTESTANT_2UNIT => 5,
	PROTESTANT_4UNIT => 2,
	SCOTLAND_1UNIT => 2,
	SCOTLAND_2UNIT => 1,
	VENICE_1UNIT => 1,
	VENICE_2UNIT => 1,
	BRANDON => 1,
	CHARLES_V => 1,
	DUDLEY => 1,
	DUKE_ALVA => 1,
	FERDINAND => 1,
	FRANCIS_I => 1,
	HENRY_II => 1,
	HENRY_VIII => 1,
	IBRAHIM => 1,
	JOHN_FREDERICK => 1,
	MAURICE_OF_SAXONY => 1,
	MONTMORENCY => 1,
	PHILIP_HESSE => 1,
	RENEGADE => 1,
	SULEIMAN => 1,
	ENGLISH_SQUADRON => 5,
	FRENCH_SQUADRON => 5,
	GENOESE_SQAUADRON => 1,
	HABSBURG_SQUADRON => 6,
	OTTOMAN_SQUADRON => 9,
	PAPACY_SQUADRON => 2,
	SCOTTISH_SQUADRON => 1,
	VENETIAN_SQUADRON => 4,
	ANDREA_DORIA => 1,
	BARBAROSSA => 1,
	DRAGUT => 1,
	ALLIED => 18,
	AT_WAR => 30,
	UNREST => 100,
	VP_ENGLAND => 1,
	VP_FRANCE => 1,
	VP_HABSBURG => 1,
	VP_OTTOMAN => 1,
	VP_PAPACY => 1,
	VP_PROTESTANT => 1,
	LOANED_ENGLAND => 28,
	LOANED_FRANCE => 28,
	LOANED_HABSBURG => 27,
	LOANED_OTTOMAN => 22,
	LOANED_PAPACY => 22,
	CALVIN_REFORMER => 1,
	CRANMER_REFORMER => 1,
	LUTHER_REFORMER => 1,
	ZWINGLI_REFORMER => 1,
	ALEANDER => 1,
	CAJETAN => 1,
	CAMPEGGIO => 1,
	CANISIUS => 1,
	CARAFFA => 1,
	CONTARINI => 1,
	ECK => 1,
	FABER => 1,
	GARDINER => 1,
	LOYOLA => 1,
	POLE => 1,
	TETZEL => 1,
	BUCER => 1,
	BULLINGER => 1,
	CALVIN => 1,
	CARLSTADT => 1,
	COP => 1,
	COVERDALE => 1,
	CRANMER => 1,
	FAREL => 1,
	KNOX => 1,
	LATIMER => 1,
	LUTHER => 1,
	MELANCHTHON => 1,
	OEKOLAMPADIUS => 1,
	OLIVETAN => 1,
	TYNDALE => 1,
	WISHART => 1,
	ZWINGLI => 1,
	ENGLISH_EXPLORATION => 1,
	FRENCH_EXPLORATION => 1,
	HABSBURG_EXPLORATION => 1,
	CABOT_ENG => 1,
	CABOT_FRE => 1,
	CABOT_HAB => 1,
	CARTIER => 1,
	CHANCELLOR => 1,
	DE_VACA => 1,
	DE_SOTO => 1,
	LEON => 1,
	MAGELLAN => 1,
	NARVAEZ => 1,
	ORELLANA => 1,
	ROBERVAL => 1,
	RUT => 1,
	VERRAZANO => 1,
	WILLOUGHBY => 1,
	CHARLESBOURG => 1,
	CUBA => 1,
	HISPANIOLA => 1,
	JAMESTOWN => 1,
	MONTREAL => 1,
	POTOSI => 1,
	PUERTO_RICO => 1,
	ROANOKE => 1,
	HABSBURG_CONQUEST => 1,
	ENGLISH_CONQUEST => 2,
	FRENCH_CONQUEST => 2,
	CORDOVA => 1,
	CORONADO => 1,
	CORTEZ => 1,
	MONTEJO => 1,
	PIZARRO => 1,
	ENGLISH_PROT_COUNTER => 1,
	PROTESTANT_SPACES => 1,
	TURN => 1,
	MINUS_ONE_CARD => 7,
	GREAT_LAKES_1VP => 1,
	MISSISSIPPI_RIVER_1VP => 1,
	ST_LAWRENCE_RIVER_1VP => 1,
	AMAZON_RIVER_2VP => 1,
	PACIFIC_STRAIT_1VP => 1,
	CIRCUMNAVIGATION_3VP => 1,
	MAYA_1VP => 1,
	AZTECS_2VP => 1,
	INCA_2VP => 1,
	BIBLE_ENG_1VP => 1,
	BIBLE_FRE_1VP => 1,
	BIBLE_GER_1VP => 1,
	CHATEAUX_VP => 1,
	PIRACY_VP => 1,
	ST_PETERS_VP => 1,
	COPERNICUS_1VP => 1,
	COPERNICUS_2VP => 1,
	EDWARD_5VP => 1,
	ELIZABETH_2VP => 1,
	GONZAGA_1VP => 1,
	SERVETUS_1VP => 1,
	MASTER_OF_ITALY_1VP => 9,
	MASTER_OF_ITALY_2VP => 9,
	WAR_WINNER_1VP => 1,
	WAR_WINNER_2VP => 1,
	PHONYSCOTLAND_MINUS1 => 1,
	PHONYVENICE_MINUS1 => 1,
	ANNE_BOLEYN => 1,
	ANNE_CLEVES => 1,
	CATHERINE_ARAGON => 1,
	JANE_SEYMOUR => 1,
	KATHERINE_PARR => 1,
	KATHRYN_HOWARD => 1,
	HENRY_MARITAL_STATUS => 1,
	BIBLE_ENGLISH => 1,
	BIBLE_FRENCH => 1,
	BIBLE_GERMAN => 1,
	NEW_TESTAMENT_ENGLISH => 1,
	NEW_TESTAMENT_FRENCH => 1,
	NEW_TESTAMENT_GERMAN => 1,
	ST_PETERS_CP => 1,
	AUGSBURG_CONFESSION => 1,
	PRINTING_PRESS => 1,
	COLONIAL_GOVERNOR => 3,
	GALLEONS => 3,
	PLANTATIONS => 3,
	PIRACY => 1,
	NATIVE_UPRISING => 3,
	RAIDER_ENGLISH => 1,
	RAIDER_FRENCH => 1,
	RAIDER_PROTESTANT => 1,
	MERCATOR_MAP => 1,
	SMALLPOX => 1,
	THOMAS_MORE => 1,
	WARTBURG => 1,
	EXCOMMUNICATED => 7,
	FORTRESS => 9,
	PIRATE_HAVEN => 2,
	JESUIT_UNIVERSITY => 1,
];

$this->board_locations = [
	TURN_TRACK_1 => [
		"x" => 3862,
		"y" => 3095,
	],
];

$this->cards = [
	CARD_JANISSARIES => [
		"class_name" => "Janissaries",
		"name" => "Janissaries",
		"type" => HOME_CARD,
		"cp" => 5,
	],
	CARD_HOLY_ROMAN_EMPEROR => [
		"class_name" => "HolyRomanEmperor",
		"name" => "Holy Roman Emperor",
		"type" => HOME_CARD,
		"cp" => 5,
	],
	CARD_SIX_WIVES_OF_HENRY_VIII => [
		"class_name" => "SixWives",
		"name" => "Six Wives of Henry VIII",
		"type" => HOME_CARD,
		"cp" => 5,
	],
	CARD_PATRON_OF_THE_ARTS => [
		"class_name" => "PatronArts",
		"name" => "Patron of the Arts",
		"type" => HOME_CARD,
		"cp" => 5,
	],
	CARD_PAPAL_BULL => [
		"class_name" => "PapalBull",
		"name" => "Papal Bull",
		"type" => HOME_CARD,
		"cp" => 4,
	],
	CARD_LEIPZIG_DEBATE => [
		"class_name" => "LeipzigDebate",
		"name" => "Leipzig Debate",
		"type" => HOME_CARD,
		"cp" => 3,
	],
	CARD_HERE_I_STAND => [
		"class_name" => "HereIStand",
		"name" => "Here I Stand",
		"type" => HOME_CARD,
		"cp" => 5,
	],
	CARD_LUTHER_95_THESES => [
		"class_name" => "LutherTheses",
		"name" => "Luther's 95 Theses",
		"type" => MANDATORY_CARD,
		"cp" => 0,
		"remove" => "Yes",
		"scenario" => 1517,
	],
];