<?php
namespace HIS;

trait AdditionalStaticTrait {
	function getPowerUnits() {
		return [
			OTTOMAN => [
				REGULAR => [1 => OTTOMAN_1UNIT, 2 => OTTOMAN_2UNIT, 4 => OTTOMAN_4UNIT, 6 => OTTOMAN_6UNIT],
				MERC => [1 => OTTOMAN_1UNIT, 2 => OTTOMAN_2UNIT, 4 => OTTOMAN_4UNIT, 6 => OTTOMAN_6UNIT],
				NAVAL => OTTOMAN_SQUADRON,
			],
			HAPSBURG => [
				REGULAR => [1 => HAPSBURG_1UNIT, 2 => HAPSBURG_2UNIT, 4 => HAPSBURG_4UNIT, 6 => HAPSBURG_6UNIT],
				MERC => [1 => HAPSBURG_1UNIT, 2 => HAPSBURG_2UNIT, 4 => HAPSBURG_4UNIT, 6 => HAPSBURG_6UNIT],
				NAVAL => HAPSBURG_SQUADRON,
			],
			ENGLAND => [
				REGULAR => [1 => ENGLAND_1UNIT, 2 => ENGLAND_2UNIT, 4 => ENGLAND_4UNIT, 6 => ENGLAND_6UNIT],
				MERC => [1 => ENGLAND_1UNIT, 2 => ENGLAND_2UNIT, 4 => ENGLAND_4UNIT, 6 => ENGLAND_6UNIT],
				NAVAL => ENGLISH_SQUADRON,
			],
			FRANCE => [
				REGULAR => [1 => FRANCE_1UNIT, 2 => FRANCE_2UNIT, 4 => FRANCE_4UNIT, 6 => FRANCE_6UNIT],
				MERC => [1 => FRANCE_1UNIT, 2 => FRANCE_2UNIT, 4 => FRANCE_4UNIT, 6 => FRANCE_6UNIT],
				NAVAL => FRENCH_SQUADRON,
			],
			PAPACY => [
				REGULAR => [1 => PAPACY_1UNIT, 2 => PAPACY_2UNIT, 4 => PAPACY_4UNIT],
				MERC => [1 => PAPACY_1UNIT, 2 => PAPACY_2UNIT, 4 => PAPACY_4UNIT],
				NAVAL => PAPACY_SQUADRON,
			],
			PROTESTANT => [
				REGULAR => [1 =>PROTESTANT_1UNIT, 2 => PROTESTANT_2UNIT, 4 => PROTESTANT_4UNIT],
				MERC => [1 =>PROTESTANT_1UNIT, 2 => PROTESTANT_2UNIT, 4 => PROTESTANT_4UNIT],
			],
			MINOR_SCOTLAND => [
				REGULAR => [1 => SCOTLAND_1UNIT],
				NAVAL => SCOTTISH_SQUADRON,
			],
			MINOR_GENOA => [
				REGULAR => [1 => GENOA_1UNIT],
				NAVAL => GENOESE_SQAUADRON,
			],
			MINOR_VENICE => [
				REGULAR => [1 => VENICE_1UNIT],
				NAVAL => VENETIAN_SQUADRON
			],
			MINOR_HUNGARY => [
				REGULAR => [1 => HUNGARY_1UNIT, 4 => HUNGARY_4UNIT],//placing tokens of denomination 2 will get wired
			]
		];
	}
}