<?php

require_once 'generated_constants.inc.php';
/*
 * ST constants
 */
const ST_GAME_SETUP = 1;
const ST_PICK_CARD = 2;
const ST_IMPULSE_ACTIONS = 3;
const ST_DECLARE_FORMATION = 4;
const ST_DECLARE_DESTINATION = 5;
const ST_FIND_MOVEMENT_RESPONSES = 6;
const ST_FIND_INTERCEPTIONS = 7;
const ST_INTERCEPT_INTENT = 8;
const ST_ROLL_INTERCEPTION = 9;
const ST_MOVE_FORMATION = 10;
const ST_FIND_AVOID = 11;
const ST_AVOID_INTENT = 12;
const ST_DECLARE_AVOID_DESTINATION = 13;
const ST_ROLL_AVOID = 14;
const ST_FIND_WITHDRAW = 15;
const ST_WITHDRAW_INTENT = 16;
const ST_FIND_BATTLE = 17;
const ST_FIELD_BATTLE = 18;
const ST_FIND_FIELD_BATTLE_RESPONSES = 19;
const ST_FIELD_BATTLE_DICE = 20;
const ST_FIELD_BATTLE_CARD = 21;
const ST_PLAY_FIELD_BATTLE_CARD = 22;
const ST_ROLL_FIELD_BATTLE_DICE = 23;
const ST_PLAY_JANISSARIES = 24;
const ST_DECLARE_FIELD_BATTLE_WINNER = 25;
const ST_FIELD_BATTLE_CASUALTIES = 26;
const ST_TAKE_FIELD_BATTLE_CASUALTIES = 27;
const ST_FIELD_BATTLE_CAPTURE_LEADERS = 28;
const ST_FIELD_BATTLE_RETREATS = 29;
const ST_DECLARE_RETREAT_DESTINATION = 30;
const ST_FIND_SIEGE = 31;
const ST_CONCLUDE_FIELD_BATTLE = 32;
const ST_MOVEMENT_RESPONSE = 33;
const ST_FIELD_BATTLE_RESPONSE = 34;
const ST_NEXT_PLAYER = 35;
const ST_BUY_UNIT = 36;
const ST_CP_REFORMATION_ATTEMPS = 37;
const ST_DISCARD = 38;

const ST_END_GAME = 99;

const ST_EVT_Janissaries = 101;
const ST_EVT_HOLYROMAN = 102;
const ST_EVT_SIXWIVESOFHENRY = 103;
const ST_EVT_SixWIVES_FRANCE_INTERVENTION = 104;
const ST_EVT_PATRONOFARTS = 105;
const ST_EVT_PAPAL_BULL = 106;


/*
 * Powers constants
 */
const FRANCE = 'france';
const HAPSBURG = 'hapsburg';
const OTTOMAN = 'ottoman';
const ENGLAND = 'england';
const PAPACY = 'papacy';
const PROTESTANT = 'protestant';
const MINOR_VENICE = 'venice';
const MINOR_SCOTLAND = 'scotland';
const MINOR_HUNGARY = 'hungary';
const MINOR_GENOA = 'genoa';
const INDEPENDENT = 'independent';
const OTHER = 'other';
const VP = 'vp';

/*
 * Language constants
 */
const SPANISH = 0;
const ENGLISH = 1;
const FRENCH = 2;
const GERMAN = 3;
const ITALIAN = 4;

/*
 * Token state constants
 */
const BACK = 'back';
const FRONT = 0;
const FLIPPED = 1;

/*
 * Token Type constants
 */
const REGULAR = 0;
const MERC = 1;
const SHIP = 2;

/*
 * Battle constants
 */
const ATTACKER = 'attacker';
const DEFENDER = 'defender';

/*
 * Card type constants
 */
const HOME_CARD = 0;
const MANDATORY_CARD = 1;
const COMBAT_CARD = 2;
const RESPONSE_CARD = 3;
const EVENT_CARD = 4;
const DIPLOMACY_CARD = 5;


/*
 * tracks
 * def strTrack(strName, intMax):
 *  return f"const {strName}_TRACK = [" + ", ".join([str(i) + " => " + strName+str(i) for i in range(0, intMax+1)]) + "];"
 */
const TURN_TRACK_TOKENS = [TURN];
const TURN_TRACK_TRACK = [1 => TURN_TRACK_1, 2 => TURN_TRACK_2, 3 => TURN_TRACK_3, 4 => TURN_TRACK_4, 5 => TURN_TRACK_5, 
    6 => TURN_TRACK_6, 7 => TURN_TRACK_7, 8 => TURN_TRACK_8, 9 => TURN_TRACK_9];

const VICTORY_TRACK_TOKENS = [VP_OTTOMAN, VP_HAPSBURG, VP_ENGLAND, VP_FRANCE, VP_PAPACY, VP_PROTESTANT];
const VICTORY_TRACK = [0 => VICTORY_TRACK_0, 1 => VICTORY_TRACK_1, 2 => VICTORY_TRACK_2, 3 => VICTORY_TRACK_3, 4 => VICTORY_TRACK_4, 
    5 => VICTORY_TRACK_5, 6 => VICTORY_TRACK_6, 7 => VICTORY_TRACK_7, 8 => VICTORY_TRACK_8, 9 => VICTORY_TRACK_9, 10 => VICTORY_TRACK_10, 
    11 => VICTORY_TRACK_11, 12 => VICTORY_TRACK_12, 13 => VICTORY_TRACK_13, 14 => VICTORY_TRACK_14, 15 => VICTORY_TRACK_15, 
    16 => VICTORY_TRACK_16, 17 => VICTORY_TRACK_17, 18 => VICTORY_TRACK_18, 19 => VICTORY_TRACK_19, 20 => VICTORY_TRACK_20, 
    21 => VICTORY_TRACK_21, 22 => VICTORY_TRACK_22, 23 => VICTORY_TRACK_23, 24 => VICTORY_TRACK_24, 25 => VICTORY_TRACK_25, 
    26 => VICTORY_TRACK_26, 27 => VICTORY_TRACK_27, 28 => VICTORY_TRACK_28, 29 => VICTORY_TRACK_29];

const PIRACY_TRACK_TOKENS = [PIRACY_VP];
const PIRACY_TRACK = [0 => PIRACY_0, 1 => PIRACY_1, 2 => PIRACY_2, 3 => PIRACY_3, 4 => PIRACY_4, 5 => PIRACY_5, 6 => PIRACY_6, 
    7 => PIRACY_7, 8 => PIRACY_8, 9 => PIRACY_9, 10 => PIRACY_10];

const PROTESTANT_SPACES_TRACK_TOKENS = [ENGLISH_PROT_COUNTER, PROTESTANT_SPACES];
const PROTESTANT_SPACES_TRACK = [0 => PROTESTANT_SPACES_0, 1 => PROTESTANT_SPACES_1, 2 => PROTESTANT_SPACES_2, 3 => PROTESTANT_SPACES_3, 4 => PROTESTANT_SPACES_4, 5 => PROTESTANT_SPACES_5, 
    6 => PROTESTANT_SPACES_6, 7 => PROTESTANT_SPACES_7, 8 => PROTESTANT_SPACES_8, 9 => PROTESTANT_SPACES_9, 10 => PROTESTANT_SPACES_10, 11 => PROTESTANT_SPACES_11, 12 => PROTESTANT_SPACES_12, 
    13 => PROTESTANT_SPACES_13, 14 => PROTESTANT_SPACES_14, 15 => PROTESTANT_SPACES_15, 16 => PROTESTANT_SPACES_16, 17 => PROTESTANT_SPACES_17, 18 => PROTESTANT_SPACES_18, 19 => PROTESTANT_SPACES_19, 
    20 => PROTESTANT_SPACES_20, 21 => PROTESTANT_SPACES_21, 22 => PROTESTANT_SPACES_22, 23 => PROTESTANT_SPACES_23, 24 => PROTESTANT_SPACES_24, 25 => PROTESTANT_SPACES_25, 26 => PROTESTANT_SPACES_26, 
    27 => PROTESTANT_SPACES_27, 28 => PROTESTANT_SPACES_28, 29 => PROTESTANT_SPACES_29, 30 => PROTESTANT_SPACES_30, 31 => PROTESTANT_SPACES_31, 32 => PROTESTANT_SPACES_32, 33 => PROTESTANT_SPACES_33, 
    34 => PROTESTANT_SPACES_34, 35 => PROTESTANT_SPACES_35, 36 => PROTESTANT_SPACES_36, 37 => PROTESTANT_SPACES_37, 38 => PROTESTANT_SPACES_38, 39 => PROTESTANT_SPACES_39, 40 => PROTESTANT_SPACES_40, 
    41 => PROTESTANT_SPACES_41, 42 => PROTESTANT_SPACES_42, 43 => PROTESTANT_SPACES_43, 44 => PROTESTANT_SPACES_44, 45 => PROTESTANT_SPACES_45, 46 => PROTESTANT_SPACES_46, 47 => PROTESTANT_SPACES_47, 
    48 => PROTESTANT_SPACES_48, 49 => PROTESTANT_SPACES_49, 50 => PROTESTANT_SPACES_50];

const MARTIAL_STATUS_TRACK_TOKENS = [HENRY_MARITAL_STATUS];
const MARITAL_STATUS_TRACK = [1 => MARITAL_STATUS_1, 2 => MARITAL_STATUS_2, 3 => MARITAL_STATUS_3, 4 => MARITAL_STATUS_4, 5 => MARITAL_STATUS_5, 
    6 => MARITAL_STATUS_6, 7 => MARITAL_STATUS_7];

const SAINT_PETERS_CP_TRACK_TOKENS = [ST_PETERS_CP];
const SAINT_PETERS_CP_TRACK = [0 => SAINT_PETERS_CP_0, 1 => SAINT_PETERS_CP_1, 2 => SAINT_PETERS_CP_2, 3 => SAINT_PETERS_CP_3, 
    4 => SAINT_PETERS_CP_4, 5 => SAINT_PETERS_CP_5];

const SAINT_PETERS_VP_TRACK_TOKENS = [ST_PETERS_VP];
const SAINT_PETERS_VP_TRACK = [0 => SAINT_PETERS_VP_0, 1 => SAINT_PETERS_VP_1, 2 => SAINT_PETERS_VP_2, 3 => SAINT_PETERS_VP_3, 
    4 => SAINT_PETERS_VP_4, 5 => SAINT_PETERS_VP_5];

const NT_TRANSLATION_TRACK_TOKENS = [NEW_TESTAMENT_ENGLISH, NEW_TESTAMENT_FRENCH, NEW_TESTAMENT_GERMAN];
const NT_TRANSLATION_TRACK = [0 => NT_TRANSLATION_0, 1 => NT_TRANSLATION_1, 2 => NT_TRANSLATION_2, 3 => NT_TRANSLATION_3, 
    4 => NT_TRANSLATION_4, 5 => NT_TRANSLATION_5, 6 => NT_TRANSLATION_6];

const BIBLE_TRANSLATION_TRACK_TOKENS = [BIBLE_ENGLISH, BIBLE_FRENCH, BIBLE_GERMAN];
const BIBLE_TRANSLATION_TRACK = [0 => BIBLE_TRANSLATION_0, 1 => BIBLE_TRANSLATION_1, 2 => BIBLE_TRANSLATION_2, 3 => BIBLE_TRANSLATION_3, 
    4 => BIBLE_TRANSLATION_4, 5 => BIBLE_TRANSLATION_5, 6 => BIBLE_TRANSLATION_6, 7 => BIBLE_TRANSLATION_7, 8 => BIBLE_TRANSLATION_8, 
    9 => BIBLE_TRANSLATION_9, 10 => BIBLE_TRANSLATION_10];

/*
 * Game options
 */

/*
 * Stats
 */
